sudo: required
dist: trusty
language: java
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y -q install tesseract-ocr tesseract-ocr-fra tesseract-ocr-jpn
  - sudo apt-get install haveged && sudo service haveged start
env:
  global:
    - TESSDATA_PREFIX=/usr/share/tesseract-ocr
    - LC_NUMERIC=C
before_script:
  - cd docs-parent